import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./components/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import ThemeRegistry from "./components/ThemeRegistry";
import { AuthProvider } from "./context/AuthContext";
import { AuthInitializer } from "./context/AuthInitializer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ThemeRegistry and AuthProvider are used to wrap the children */}
        <ThemeRegistry>
          <ReduxProvider>
            <AuthInitializer>
{children}
            </AuthInitializer>
          </ReduxProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
